export const GET_SERVICE_ERROR = "FETCH_SYSTEMS_ERROR";
export const GET_SERVICE_SUCCESS = "FETCH_SYSTEMS_SUCCESS";
export const GET_SERVICE_LOADING = "FETCH_SYSTEMS_LOADING";
export const GET_SELECTED_GAME = "GET_SELECTED_GAME";

